### ISSUE TITLE
feat: add sub page

### ISSUE THREAD

**Issue by suhyeoon** [suhyeoon/Responsive-Project#1]
# 🌟Todo List
- [x] create sub page
- [x] refactor sub page code
- [x] study responsive web
